name: "Cron Build With Quarkus and Extension Mains"

on:
  schedule:
    - cron: '0 3 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'amqphub/quarkus-qpid-jms-quickstart' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17 ]
        graal: [ 21.3.0 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/quarkus
            !~/.m2/repository/org/amqphub/quarkus
          key: ${{ runner.os }}-cron-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-cron-maven
            ${{ runner.os }}-maven

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Pull Quarkus Native Builder Image (${{ matrix.graal }})
        if: matrix.graal != 'none'
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}

      - name: Build Quarkus main
        env:
          MAVEN_PL: "., io.quarkus:quarkus-bom, io.quarkus:quarkus-core-deployment, io.quarkus:quarkus-arc-deployment, io.quarkus:quarkus-netty-deployment, io.quarkus:quarkus-extension-processor, io.quarkus:quarkus-bootstrap-bom, io.quarkus:quarkus-bootstrap-bom-test, io.quarkus:quarkus-bootstrap-maven-plugin, io.quarkus:quarkus-maven-plugin, io.quarkus:quarkus-resteasy-deployment, io.quarkus:quarkus-jackson-deployment, io.quarkus:quarkus-test-artemis, io.quarkus:quarkus-junit5"
        run: |
          git clone --depth 1 --branch main https://github.com/quarkusio/quarkus.git && cd quarkus && echo "Current Quarkus commit:" $(git rev-parse HEAD)
          mvn -B -s ../.github/cron-maven-settings.xml clean install -DskipTests -DskipITs -Dformat.skip -DskipDocs -am -pl "${MAVEN_PL}"

      - name: Build Extension main against Quarkus main
        run: |
          git clone --depth 1 --branch main https://github.com/amqphub/quarkus-qpid-jms.git && cd quarkus-qpid-jms && echo "Current Quarkus Qpid JMS commit:" $(git rev-parse HEAD)
          mvn release:update-versions -DdevelopmentVersion=999-SNAPSHOT
          mvn -B clean install -DskipTests -DskipITs -Dquarkus.version=999-SNAPSHOT

      - name: Build - JVM
        run: mvn -B clean verify -Pextension-version -Dquarkus-qpid-jms.version=999-SNAPSHOT -Dquarkus-plugin.version=999-SNAPSHOT -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=999-SNAPSHOT

      - name: Build - Native
        if: matrix.graal != 'none'
        run: mvn -B clean verify -Pextension-version -Dquarkus-qpid-jms.version=999-SNAPSHOT -Dquarkus-plugin.version=999-SNAPSHOT -Dquarkus.platform.artifact-id=quarkus-bom -Dquarkus.platform.version=999-SNAPSHOT -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}
